### ISSUE TITLE
Minor Details

### ISSUE THREAD

**Issue by dominicfrost** [jerold/Catan#2]
There are some minor details that MUST be address before I can use this application. 
1. Prevent the default context menu. It's very confusing when a right click does something in your application, but a context menu pops up in the way.
2. How the heck do I create a game from scratch? When I press new game, I expect to have an empty game board. Not some pre-generated thing.

**Comment by jerold** [comment]
To be addressed in the following tickets:
https://github.com/jerold/Catan/issues/2
https://github.com/jerold/Catan/issues/3
