### ISSUE TITLE
Prevent browser context menu from appearing

### ISSUE THREAD

**Issue by jerold** [jerold/Catan#4]
Right click should not present the user with the browser's default context menu.

**Comment by ghost** [comment]
Do you want a message saying "Right Click disabled" ? or something like that?

**Comment by jerold** [comment]
No alert needed. The current unwanted ux this ticket aims to fix is when the user uses the right mouse button to bring up the tile's radial menu, on mouseUp the context menu appears. Desired effect would be that on mouseUp, the radial menu disappears, and no context menu appears.

**Comment by jerold** [comment]
Addressed in https://github.com/jerold/Catan/pull/10
